DATA_PATH = "C:/Users/alberto/Documents/datasets/global-wheat-detection"
TRAIN_BATCH_SIZE = 4
VALID_BATCH_SIZE = 2
NUM_CLASSES = 2 # 1 class (wheat) + background
NUM_WORKERS = 0
EPOCHS = 10
DEVICE = "cuda"
LR = 0.001
DEBUG = True